/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ALEJO
 */
public class viewVistaProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaUsuarios
     */
    public viewVistaProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblProveedor = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jbtnAgregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jBtnModificar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jBtnElimina = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jBtnImprimir = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        txtBuscar = new javax.swing.JTextField();
        jCbFiltroRol = new javax.swing.JComboBox<>();
        jBtnBuscar = new javax.swing.JButton();
        jBtnActualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(210, 215, 159));
        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setVisible(true);

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel3.setText("VISTA DE PROVEEDORES");

        jTblProveedor.setBackground(new java.awt.Color(255, 253, 227));
        jTblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Ciudad", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTblProveedor);

        jToolBar1.setBackground(new java.awt.Color(210, 215, 159));
        jToolBar1.setBorder(null);

        jbtnAgregar.setBackground(new java.awt.Color(210, 215, 159));
        jbtnAgregar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbtnAgregar.setText("AGREGAR");
        jbtnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbtnAgregar);
        jToolBar1.add(jSeparator1);

        jBtnModificar.setBackground(new java.awt.Color(210, 215, 159));
        jBtnModificar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jBtnModificar.setText("MODIFICAR");
        jToolBar1.add(jBtnModificar);
        jToolBar1.add(jSeparator2);

        jBtnElimina.setBackground(new java.awt.Color(210, 215, 159));
        jBtnElimina.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jBtnElimina.setText("ELIMINAR");
        jBtnElimina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnElimina.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnElimina);
        jToolBar1.add(jSeparator3);

        jBtnImprimir.setBackground(new java.awt.Color(210, 215, 159));
        jBtnImprimir.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jBtnImprimir.setText("IMPRIMIR REPORTE");
        jToolBar1.add(jBtnImprimir);
        jToolBar1.add(jSeparator4);

        txtBuscar.setEditable(false);
        txtBuscar.setBackground(new java.awt.Color(255, 253, 227));
        txtBuscar.setToolTipText("PUEDE BUSCAR MEDIANTE CEDULA, NOMBRE, APELLIDO O USUARIO");
        jToolBar1.add(txtBuscar);

        jCbFiltroRol.setBackground(new java.awt.Color(210, 215, 159));
        jCbFiltroRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar rol", "Gerente", "Secretaria", "Zoologo", "Cuidador" }));
        jCbFiltroRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbFiltroRolActionPerformed(evt);
            }
        });
        jToolBar1.add(jCbFiltroRol);

        jBtnBuscar.setBackground(new java.awt.Color(210, 215, 159));
        jBtnBuscar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jBtnBuscar.setText("BUSCAR");
        jToolBar1.add(jBtnBuscar);

        jBtnActualizar.setBackground(new java.awt.Color(210, 215, 159));
        jBtnActualizar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jBtnActualizar.setText("ACTUALIZAR");
        jBtnActualizar.setFocusable(false);
        jBtnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnActualizar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(228, 228, 228))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbFiltroRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbFiltroRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbFiltroRolActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnActualizar;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnElimina;
    private javax.swing.JButton jBtnImprimir;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JComboBox<String> jCbFiltroRol;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTable jTblProveedor;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtnAgregar;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    public JButton getjBtnActualizar() {
        return jBtnActualizar;
    }

    public void setjBtnActualizar(JButton jBtnActualizar) {
        this.jBtnActualizar = jBtnActualizar;
    }

    public JButton getjBtnBuscar() {
        return jBtnBuscar;
    }

    public void setjBtnBuscar(JButton jBtnBuscar) {
        this.jBtnBuscar = jBtnBuscar;
    }

    public JButton getjBtnElimina() {
        return jBtnElimina;
    }

    public void setjBtnElimina(JButton jBtnElimina) {
        this.jBtnElimina = jBtnElimina;
    }

    public JButton getjBtnImprimir() {
        return jBtnImprimir;
    }

    public void setjBtnImprimir(JButton jBtnImprimir) {
        this.jBtnImprimir = jBtnImprimir;
    }

    public JButton getjBtnModificar() {
        return jBtnModificar;
    }

    public void setjBtnModificar(JButton jBtnModificar) {
        this.jBtnModificar = jBtnModificar;
    }

    public JComboBox<String> getjCbFiltroRol() {
        return jCbFiltroRol;
    }

    public void setjCbFiltroRol(JComboBox<String> jCbFiltroRol) {
        this.jCbFiltroRol = jCbFiltroRol;
    }

    public JTable getjTblProveedor() {
        return jTblProveedor;
    }

    public void setjTblProveedor(JTable jTblProveedor) {
        this.jTblProveedor = jTblProveedor;
    }

    public JButton getJbtnAgregar() {
        return jbtnAgregar;
    }

    public void setJbtnAgregar(JButton jbtnAgregar) {
        this.jbtnAgregar = jbtnAgregar;
    }

    public JTextField getTxtBuscar() {
        return txtBuscar;
    }

    public void setTxtBuscar(JTextField txtBuscar) {
        this.txtBuscar = txtBuscar;
    }

 
}
