/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author ALEJO
 */
public class viewPantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form pantallaprincipal
     */
    public viewPantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jDPprincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnLimpiarDSK = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        barramenus = new javax.swing.JMenuBar();
        agregarpersona = new javax.swing.JMenu();
        jMIagregarPersona = new javax.swing.JMenuItem();
        jMIeliminarpersona = new javax.swing.JMenuItem();
        modificarpersona = new javax.swing.JMenuItem();
        jMIvistaEmpleado = new javax.swing.JMenuItem();
        menualimento = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        menuanimales = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MIActualizarPrecio = new javax.swing.JMenuItem();
        jMProveedor = new javax.swing.JMenu();
        jMIagregarProveedor = new javax.swing.JMenuItem();
        JMIvistaProveedor = new javax.swing.JMenuItem();
        jMProveedor1 = new javax.swing.JMenu();
        jMIagregarCliente = new javax.swing.JMenuItem();
        JMIvistaCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1150, 0));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDPprincipal.setBackground(new java.awt.Color(210, 215, 159));
        jDPprincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDPprincipal.setForeground(new java.awt.Color(210, 215, 159));
        jDPprincipal.setEnabled(false);

        javax.swing.GroupLayout jDPprincipalLayout = new javax.swing.GroupLayout(jDPprincipal);
        jDPprincipal.setLayout(jDPprincipalLayout);
        jDPprincipalLayout.setHorizontalGroup(
            jDPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 996, Short.MAX_VALUE)
        );
        jDPprincipalLayout.setVerticalGroup(
            jDPprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        jPanel3.add(jDPprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 1000, 630));

        jPanel1.setBackground(new java.awt.Color(144, 183, 125));

        btnLimpiarDSK.setBackground(new java.awt.Color(66, 133, 91));
        btnLimpiarDSK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpieza-de-datos.png"))); // NOI18N
        btnLimpiarDSK.setToolTipText("Vaciar pantalla");

        jPanel2.setBackground(new java.awt.Color(72, 56, 56));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnLimpiarDSK)
                .addContainerGap(55, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarDSK)
                .addGap(17, 17, 17))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        agregarpersona.setText("PERSONAL");

        jMIagregarPersona.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMIagregarPersona.setText("AGREGAR PERSONAL");
        agregarpersona.add(jMIagregarPersona);

        jMIeliminarpersona.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMIeliminarpersona.setText("ELIMINAR PERSONA");
        agregarpersona.add(jMIeliminarpersona);

        modificarpersona.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        modificarpersona.setText("MODIFICAR PERSONA");
        agregarpersona.add(modificarpersona);

        jMIvistaEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMIvistaEmpleado.setText("VISUALIZAR REGISTRO DEL PERSONAL");
        agregarpersona.add(jMIvistaEmpleado);

        barramenus.add(agregarpersona);

        menualimento.setText("ALIMENTO");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("AGREGAR ALIMENTO");
        menualimento.add(jMenuItem4);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem10.setText("ELIMINAR ALIMENTO");
        menualimento.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem11.setText("MODIFICAR ALIMENTO");
        menualimento.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem12.setText("VISUALIZAR REGISTRO DE ALIMENTOS");
        menualimento.add(jMenuItem12);

        barramenus.add(menualimento);

        menuanimales.setText("ANIMALES");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setText("AGREGAR ANIMAL");
        menuanimales.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem6.setText("ELIMINAR ANIMAL");
        menuanimales.add(jMenuItem6);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem8.setText("MODIFICAR ANIMAL");
        menuanimales.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem9.setText("VISUALIZAR REGISTRO DE ANIMALES");
        menuanimales.add(jMenuItem9);

        barramenus.add(menuanimales);

        jMenu1.setText("TICKETS");

        MIActualizarPrecio.setText("ACTUALIZAR PRECIO");
        jMenu1.add(MIActualizarPrecio);

        barramenus.add(jMenu1);

        jMProveedor.setText("PROVEEDOR");

        jMIagregarProveedor.setText("Agregar Proveedor");
        jMProveedor.add(jMIagregarProveedor);

        JMIvistaProveedor.setText("Visualizar registro de proveedores");
        jMProveedor.add(JMIvistaProveedor);

        barramenus.add(jMProveedor);

        jMProveedor1.setText("CLIENTE");

        jMIagregarCliente.setText("Agregar Cliente");
        jMIagregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIagregarClienteActionPerformed(evt);
            }
        });
        jMProveedor1.add(jMIagregarCliente);

        JMIvistaCliente.setText("Visualizar Clientes");
        jMProveedor1.add(JMIvistaCliente);

        barramenus.add(jMProveedor1);

        setJMenuBar(barramenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMIagregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIagregarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIagregarClienteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMIvistaCliente;
    private javax.swing.JMenuItem JMIvistaProveedor;
    private javax.swing.JMenuItem MIActualizarPrecio;
    private javax.swing.JMenu agregarpersona;
    private javax.swing.JMenuBar barramenus;
    private javax.swing.JButton btnLimpiarDSK;
    private javax.swing.JDesktopPane jDPprincipal;
    private javax.swing.JMenuItem jMIagregarCliente;
    private javax.swing.JMenuItem jMIagregarPersona;
    private javax.swing.JMenuItem jMIagregarProveedor;
    private javax.swing.JMenuItem jMIeliminarpersona;
    private javax.swing.JMenuItem jMIvistaEmpleado;
    private javax.swing.JMenu jMProveedor;
    private javax.swing.JMenu jMProveedor1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu menualimento;
    private javax.swing.JMenu menuanimales;
    private javax.swing.JMenuItem modificarpersona;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getJMIvistaProveedor() {
        return JMIvistaProveedor;
    }

    public void setJMIvistaProveedor(JMenuItem JMIvistaProveedor) {
        this.JMIvistaProveedor = JMIvistaProveedor;
    }

    public JMenuItem getMIActualizarPrecio() {
        return MIActualizarPrecio;
    }

    public void setMIActualizarPrecio(JMenuItem MIActualizarPrecio) {
        this.MIActualizarPrecio = MIActualizarPrecio;
    }

    public JMenu getAgregarpersona() {
        return agregarpersona;
    }

    public void setAgregarpersona(JMenu agregarpersona) {
        this.agregarpersona = agregarpersona;
    }

    public JMenuBar getBarramenus() {
        return barramenus;
    }

    public void setBarramenus(JMenuBar barramenus) {
        this.barramenus = barramenus;
    }

    public JDesktopPane getjDPprincipal() {
        return jDPprincipal;
    }

    public void setjDPprincipal(JDesktopPane jDPprincipal) {
        this.jDPprincipal = jDPprincipal;
    }

    public JMenuItem getjMIagregarPersona() {
        return jMIagregarPersona;
    }

    public void setjMIagregarPersona(JMenuItem jMIagregarPersona) {
        this.jMIagregarPersona = jMIagregarPersona;
    }

    public JMenuItem getjMIagregarProveedor() {
        return jMIagregarProveedor;
    }

    public void setjMIagregarProveedor(JMenuItem jMIagregarProveedor) {
        this.jMIagregarProveedor = jMIagregarProveedor;
    }

    public JMenuItem getjMIeliminarpersona() {
        return jMIeliminarpersona;
    }

    public void setjMIeliminarpersona(JMenuItem jMIeliminarpersona) {
        this.jMIeliminarpersona = jMIeliminarpersona;
    }

    public JMenuItem getjMIvistaEmpleado() {
        return jMIvistaEmpleado;
    }

    public void setjMIvistaEmpleado(JMenuItem jMIvistaEmpleado) {
        this.jMIvistaEmpleado = jMIvistaEmpleado;
    }

    public JMenu getjMProveedor() {
        return jMProveedor;
    }

    public void setjMProveedor(JMenu jMProveedor) {
        this.jMProveedor = jMProveedor;
    }

    public JMenu getMenualimento() {
        return menualimento;
    }

    public void setMenualimento(JMenu menualimento) {
        this.menualimento = menualimento;
    }

    public JMenu getMenuanimales() {
        return menuanimales;
    }

    public void setMenuanimales(JMenu menuanimales) {
        this.menuanimales = menuanimales;
    }

    public JMenuItem getModificarpersona() {
        return modificarpersona;
    }

    public void setModificarpersona(JMenuItem modificarpersona) {
        this.modificarpersona = modificarpersona;
    }

    public JMenuItem getJMIvistaCliente() {
        return JMIvistaCliente;
    }

    public void setJMIvistaCliente(JMenuItem JMIvistaCliente) {
        this.JMIvistaCliente = JMIvistaCliente;
    }

    public JMenuItem getjMIagregarCliente() {
        return jMIagregarCliente;
    }

    public void setjMIagregarCliente(JMenuItem jMIagregarCliente) {
        this.jMIagregarCliente = jMIagregarCliente;
    }

    public JButton getBtnLimpiarDSK() {
        return btnLimpiarDSK;
    }

    public void setBtnLimpiarDSK(JButton btnLimpiarDSK) {
        this.btnLimpiarDSK = btnLimpiarDSK;
    }
    
    

}
