/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author Bryan
 */
public class viewVentaTicket extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewVentaTicket
     */
    public viewVentaTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnConfirmarCompra = new javax.swing.JButton();
        btnCancelarCompra = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidoCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        txtCedulaCliente = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        txtCorreoCliente = new javax.swing.JTextField();
        txtDireccionCliente = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        btnAgregarCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtSUBTOTAL = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        txtDESCUENTO = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        txtTOTAL = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        txtPrecioAdultoMayor = new javax.swing.JLabel();
        btnMenosAdultoMayor = new javax.swing.JButton();
        txtCantidadAdultoMayor = new javax.swing.JLabel();
        btnMasAdultoMayor = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        txtTotalAdultoMayor = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        txtPrecioAdulto = new javax.swing.JLabel();
        btnMenosAdulto = new javax.swing.JButton();
        txtCantidadAdulto = new javax.swing.JLabel();
        btnMasAdulto = new javax.swing.JButton();
        jLabel63 = new javax.swing.JLabel();
        txtTotalAdulto = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        txtPrecioNiño = new javax.swing.JLabel();
        btnMenosNiño = new javax.swing.JButton();
        txtCantidadNiño = new javax.swing.JLabel();
        btnMasNiño = new javax.swing.JButton();
        jLabel74 = new javax.swing.JLabel();
        txtTotalNiño = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setBorder(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("VENTA DE BOLETOS");

        btnConfirmarCompra.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnConfirmarCompra.setText("CONFIRMAR COMPRA");

        btnCancelarCompra.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnCancelarCompra.setText("CANCELAR");

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel41.setText("Cedula:");

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel42.setText("Nombre:");

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel43.setText("Apellido:");

        jLabel51.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel51.setText("Correo:");

        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel44.setText("Telefono:");

        jLabel52.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel52.setText("Direccion:");

        btnAgregarCliente.setText("+Cliente");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel44))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42)
                            .addComponent(jLabel52)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel41)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCedulaCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel51))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtDireccionCliente))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(txtApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoCliente)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("SUBTOTAL");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("TOTAL");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("DESCUENTO");

        jSeparator1.setForeground(new java.awt.Color(242, 242, 242));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setForeground(new java.awt.Color(242, 242, 242));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtSUBTOTAL.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtSUBTOTAL.setText("precio");

        jLabel130.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel130.setText("$");

        txtDESCUENTO.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDESCUENTO.setText("precio");

        jLabel132.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel132.setText("$");

        txtTOTAL.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTOTAL.setText("precio");

        jLabel134.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel134.setText("$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel130)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSUBTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel132)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDESCUENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel134)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel132)
                            .addComponent(txtDESCUENTO)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel134)
                            .addComponent(txtTOTAL)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel130)
                            .addComponent(txtSUBTOTAL))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel37.setText("ADULTOS MAYORES");
        jPanel7.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 10, -1, -1));

        jLabel55.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel55.setText("$");
        jPanel7.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        txtPrecioAdultoMayor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPrecioAdultoMayor.setText("precio");
        jPanel7.add(txtPrecioAdultoMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 50, -1));

        btnMenosAdultoMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo-menos-de-una-linea-en-posicion-horizontal.png"))); // NOI18N
        jPanel7.add(btnMenosAdultoMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 30, -1));

        txtCantidadAdultoMayor.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtCantidadAdultoMayor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantidadAdultoMayor.setText("0");
        jPanel7.add(txtCantidadAdultoMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 40, 30));

        btnMasAdultoMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
        jPanel7.add(btnMasAdultoMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 30, 30));

        jLabel58.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel58.setText("$");
        jPanel7.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        txtTotalAdultoMayor.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtTotalAdultoMayor.setText("precio");
        jPanel7.add(txtTotalAdultoMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 50, -1));

        jPanel9.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel53.setText("ADULTOS                   ");
        jPanel9.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        jLabel60.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel60.setText("$");
        jPanel9.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        txtPrecioAdulto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPrecioAdulto.setText("precio");
        jPanel9.add(txtPrecioAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 50, -1));

        btnMenosAdulto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo-menos-de-una-linea-en-posicion-horizontal.png"))); // NOI18N
        jPanel9.add(btnMenosAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 30, 30));

        txtCantidadAdulto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtCantidadAdulto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantidadAdulto.setText("0");
        jPanel9.add(txtCantidadAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 40, 30));

        btnMasAdulto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
        jPanel9.add(btnMasAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 30, 30));

        jLabel63.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel63.setText("$");
        jPanel9.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        txtTotalAdulto.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtTotalAdulto.setText("precio");
        jPanel9.add(txtTotalAdulto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 50, -1));

        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel70.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel70.setText("NIÑOS                         ");
        jPanel11.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 10, -1, -1));

        jLabel71.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel71.setText("$");
        jPanel11.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        txtPrecioNiño.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPrecioNiño.setText("precio");
        jPanel11.add(txtPrecioNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 50, -1));

        btnMenosNiño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo-menos-de-una-linea-en-posicion-horizontal.png"))); // NOI18N
        jPanel11.add(btnMenosNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 30, 30));

        txtCantidadNiño.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtCantidadNiño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantidadNiño.setText("0");
        jPanel11.add(txtCantidadNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 40, 30));

        btnMasNiño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
        jPanel11.add(btnMasNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 30, 30));

        jLabel74.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel74.setText("$");
        jPanel11.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        txtTotalNiño.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtTotalNiño.setText("precio");
        jPanel11.add(txtTotalNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 50, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("TOTAL");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setText("TUS TICKETS");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("CANTIDAD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel9)
                                .addGap(33, 33, 33)))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(283, 283, 283))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCancelarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConfirmarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(113, 113, 113))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(btnConfirmarCompra)
                        .addGap(26, 26, 26)
                        .addComponent(btnCancelarCompra)
                        .addGap(180, 180, 180))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnCancelarCompra;
    private javax.swing.JButton btnConfirmarCompra;
    private javax.swing.JButton btnMasAdulto;
    private javax.swing.JButton btnMasAdultoMayor;
    private javax.swing.JButton btnMasNiño;
    private javax.swing.JButton btnMenosAdulto;
    private javax.swing.JButton btnMenosAdultoMayor;
    private javax.swing.JButton btnMenosNiño;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JLabel txtCantidadAdulto;
    private javax.swing.JLabel txtCantidadAdultoMayor;
    private javax.swing.JLabel txtCantidadNiño;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JLabel txtDESCUENTO;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JLabel txtPrecioAdulto;
    private javax.swing.JLabel txtPrecioAdultoMayor;
    private javax.swing.JLabel txtPrecioNiño;
    private javax.swing.JLabel txtSUBTOTAL;
    private javax.swing.JLabel txtTOTAL;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JLabel txtTotalAdulto;
    private javax.swing.JLabel txtTotalAdultoMayor;
    private javax.swing.JLabel txtTotalNiño;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregarCliente() {
        return btnAgregarCliente;
    }

    public void setBtnAgregarCliente(JButton btnAgregarCliente) {
        this.btnAgregarCliente = btnAgregarCliente;
    }

    public JButton getBtnCancelarCompra() {
        return btnCancelarCompra;
    }

    public void setBtnCancelarCompra(JButton btnCancelarCompra) {
        this.btnCancelarCompra = btnCancelarCompra;
    }

    public JButton getBtnConfirmarCompra() {
        return btnConfirmarCompra;
    }

    public void setBtnConfirmarCompra(JButton btnConfirmarCompra) {
        this.btnConfirmarCompra = btnConfirmarCompra;
    }

    public JButton getBtnMasAdulto() {
        return btnMasAdulto;
    }

    public void setBtnMasAdulto(JButton btnMasAdulto) {
        this.btnMasAdulto = btnMasAdulto;
    }

    public JButton getBtnMasAdultoMayor() {
        return btnMasAdultoMayor;
    }

    public void setBtnMasAdultoMayor(JButton btnMasAdultoMayor) {
        this.btnMasAdultoMayor = btnMasAdultoMayor;
    }

    public JButton getBtnMasNiño() {
        return btnMasNiño;
    }

    public void setBtnMasNiño(JButton btnMasNiño) {
        this.btnMasNiño = btnMasNiño;
    }

    public JButton getBtnMenosAdulto() {
        return btnMenosAdulto;
    }

    public void setBtnMenosAdulto(JButton btnMenosAdulto) {
        this.btnMenosAdulto = btnMenosAdulto;
    }

    public JButton getBtnMenosAdultoMayor() {
        return btnMenosAdultoMayor;
    }

    public void setBtnMenosAdultoMayor(JButton btnMenosAdultoMayor) {
        this.btnMenosAdultoMayor = btnMenosAdultoMayor;
    }

    public JButton getBtnMenosNiño() {
        return btnMenosNiño;
    }

    public void setBtnMenosNiño(JButton btnMenosNiño) {
        this.btnMenosNiño = btnMenosNiño;
    }

    public JTextField getTxtApellidoCliente() {
        return txtApellidoCliente;
    }

    public void setTxtApellidoCliente(JTextField txtApellidoCliente) {
        this.txtApellidoCliente = txtApellidoCliente;
    }

    public JLabel getTxtCantidadAdulto() {
        return txtCantidadAdulto;
    }

    public void setTxtCantidadAdulto(JLabel txtCantidadAdulto) {
        this.txtCantidadAdulto = txtCantidadAdulto;
    }

    public JLabel getTxtCantidadAdultoMayor() {
        return txtCantidadAdultoMayor;
    }

    public void setTxtCantidadAdultoMayor(JLabel txtCantidadAdultoMayor) {
        this.txtCantidadAdultoMayor = txtCantidadAdultoMayor;
    }

    public JLabel getTxtCantidadNiño() {
        return txtCantidadNiño;
    }

    public void setTxtCantidadNiño(JLabel txtCantidadNiño) {
        this.txtCantidadNiño = txtCantidadNiño;
    }

    public JTextField getTxtCedulaCliente() {
        return txtCedulaCliente;
    }

    public void setTxtCedulaCliente(JTextField txtCedulaCliente) {
        this.txtCedulaCliente = txtCedulaCliente;
    }

    public JTextField getTxtCorreoCliente() {
        return txtCorreoCliente;
    }

    public void setTxtCorreoCliente(JTextField txtCorreoCliente) {
        this.txtCorreoCliente = txtCorreoCliente;
    }

    public JLabel getTxtDESCUENTO() {
        return txtDESCUENTO;
    }

    public void setTxtDESCUENTO(JLabel txtDESCUENTO) {
        this.txtDESCUENTO = txtDESCUENTO;
    }

    public JTextField getTxtDireccionCliente() {
        return txtDireccionCliente;
    }

    public void setTxtDireccionCliente(JTextField txtDireccionCliente) {
        this.txtDireccionCliente = txtDireccionCliente;
    }

    public JTextField getTxtNombreCliente() {
        return txtNombreCliente;
    }

    public void setTxtNombreCliente(JTextField txtNombreCliente) {
        this.txtNombreCliente = txtNombreCliente;
    }

    public JLabel getTxtPrecioAdulto() {
        return txtPrecioAdulto;
    }

    public void setTxtPrecioAdulto(JLabel txtPrecioAdulto) {
        this.txtPrecioAdulto = txtPrecioAdulto;
    }

    public JLabel getTxtPrecioAdultoMayor() {
        return txtPrecioAdultoMayor;
    }

    public void setTxtPrecioAdultoMayor(JLabel txtPrecioAdultoMayor) {
        this.txtPrecioAdultoMayor = txtPrecioAdultoMayor;
    }

    public JLabel getTxtPrecioNiño() {
        return txtPrecioNiño;
    }

    public void setTxtPrecioNiño(JLabel txtPrecioNiño) {
        this.txtPrecioNiño = txtPrecioNiño;
    }

    public JLabel getTxtSUBTOTAL() {
        return txtSUBTOTAL;
    }

    public void setTxtSUBTOTAL(JLabel txtSUBTOTAL) {
        this.txtSUBTOTAL = txtSUBTOTAL;
    }

    public JLabel getTxtTOTAL() {
        return txtTOTAL;
    }

    public void setTxtTOTAL(JLabel txtTOTAL) {
        this.txtTOTAL = txtTOTAL;
    }

    public JTextField getTxtTelefonoCliente() {
        return txtTelefonoCliente;
    }

    public void setTxtTelefonoCliente(JTextField txtTelefonoCliente) {
        this.txtTelefonoCliente = txtTelefonoCliente;
    }

    public JLabel getTxtTotalAdulto() {
        return txtTotalAdulto;
    }

    public void setTxtTotalAdulto(JLabel txtTotalAdulto) {
        this.txtTotalAdulto = txtTotalAdulto;
    }

    public JLabel getTxtTotalNiño() {
        return txtTotalNiño;
    }

    public void setTxtTotalNiño(JLabel txtTotalNiño) {
        this.txtTotalNiño = txtTotalNiño;
    }


}
