/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.toedter.calendar.JDateChooser;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Bryan
 */
public class viewRegistroAnimal extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroAnimal
     */
    public viewRegistroAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDlgCuidador = new javax.swing.JDialog();
        lbltitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladlgCuidador = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel12 = new javax.swing.JLabel();
        txtbuscardlgCui = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnseleccionardlgCui = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jDlgHabitat = new javax.swing.JDialog();
        lbltitulo1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabladlgHabitat = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jLabel14 = new javax.swing.JLabel();
        txtbuscardlgHab = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnseleccionardlgHab = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        buttonGroupGenero = new javax.swing.ButtonGroup();
        txtidHabitatNoborrar = new javax.swing.JTextField();
        txtidCuidadorNoborrar = new javax.swing.JTextField();
        txtidAnimalNoborrar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnSeleccionarHabitat = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtTipoHabitat = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        btnSeleccionarCuidador = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtNombreCuidador = new javax.swing.JTextField();
        txtTipoSangre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblFotoAnimal = new javax.swing.JLabel();
        btnExaminarFoto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboEspecie = new javax.swing.JComboBox<>();
        btnhembra = new javax.swing.JRadioButton();
        btnmacho = new javax.swing.JRadioButton();
        txtnombreanimal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        calendarNacimiento = new com.toedter.calendar.JDateChooser();
        txtOtraEspecie = new javax.swing.JTextField();

        jDlgCuidador.setResizable(false);
        jDlgCuidador.setSize(new java.awt.Dimension(545, 310));

        lbltitulo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbltitulo.setText("SELECCIÓN DE CUIDADOR");

        tabladlgCuidador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Tipo de sangre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabladlgCuidador);

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.add(jSeparator1);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("BUSCAR:  ");
        jToolBar1.add(jLabel12);
        jToolBar1.add(txtbuscardlgCui);
        jToolBar1.add(jSeparator2);

        btnseleccionardlgCui.setText("SELECCIONAR");
        jToolBar1.add(btnseleccionardlgCui);
        jToolBar1.add(jSeparator3);

        javax.swing.GroupLayout jDlgCuidadorLayout = new javax.swing.GroupLayout(jDlgCuidador.getContentPane());
        jDlgCuidador.getContentPane().setLayout(jDlgCuidadorLayout);
        jDlgCuidadorLayout.setHorizontalGroup(
            jDlgCuidadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDlgCuidadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltitulo)
                .addGap(66, 66, 66))
        );
        jDlgCuidadorLayout.setVerticalGroup(
            jDlgCuidadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDlgCuidadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
        );

        jDlgHabitat.setResizable(false);
        jDlgHabitat.setSize(new java.awt.Dimension(545, 310));

        lbltitulo1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbltitulo1.setText("SELECCIÓN DE HABITAT");

        tabladlgHabitat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Tipo", "Ubicacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabladlgHabitat);

        jToolBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.setFloatable(false);
        jToolBar2.add(jSeparator4);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("BUSCAR:  ");
        jToolBar2.add(jLabel14);
        jToolBar2.add(txtbuscardlgHab);
        jToolBar2.add(jSeparator5);

        btnseleccionardlgHab.setText("SELECCIONAR");
        jToolBar2.add(btnseleccionardlgHab);
        jToolBar2.add(jSeparator6);

        javax.swing.GroupLayout jDlgHabitatLayout = new javax.swing.GroupLayout(jDlgHabitat.getContentPane());
        jDlgHabitat.getContentPane().setLayout(jDlgHabitatLayout);
        jDlgHabitatLayout.setHorizontalGroup(
            jDlgHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDlgHabitatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltitulo1)
                .addGap(82, 82, 82))
        );
        jDlgHabitatLayout.setVerticalGroup(
            jDlgHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDlgHabitatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
        );

        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(970, 630));

        jPanel1.setBackground(new java.awt.Color(210, 215, 159));
        jPanel1.setPreferredSize(new java.awt.Dimension(970, 630));

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 40)); // NOI18N
        jLabel3.setText("DATOS ADICIONALES");

        btnCancelar.setBackground(new java.awt.Color(210, 215, 159));
        btnCancelar.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-x.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);

        btnAgregar.setBackground(new java.awt.Color(210, 215, 159));
        btnAgregar.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprobado (1).png"))); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.setBorder(null);

        jPanel2.setBackground(new java.awt.Color(210, 215, 159));

        jLabel20.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel20.setText("HABITAD");

        btnSeleccionarHabitat.setBackground(new java.awt.Color(255, 253, 227));
        btnSeleccionarHabitat.setText("SELECCIONAR");

        jLabel21.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel21.setText("TIPO:");

        jLabel22.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel22.setText("UBICACION:");

        txtTipoHabitat.setBackground(new java.awt.Color(255, 253, 227));

        txtUbicacion.setBackground(new java.awt.Color(255, 253, 227));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSeleccionarHabitat)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTipoHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(btnSeleccionarHabitat))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(210, 215, 159));

        jLabel24.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel24.setText("CUIDADOR");

        btnSeleccionarCuidador.setBackground(new java.awt.Color(255, 253, 227));
        btnSeleccionarCuidador.setText("SELECCIONAR");

        jLabel25.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel25.setText("NOMBRE:");

        jLabel27.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel27.setText("TIPO DE SANGRE:");

        txtNombreCuidador.setBackground(new java.awt.Color(255, 253, 227));

        txtTipoSangre.setBackground(new java.awt.Color(255, 253, 227));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSeleccionarCuidador))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addGap(18, 18, 18)
                            .addComponent(txtNombreCuidador)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionarCuidador)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtNombreCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tortuga (2) (1).png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jLabel10.setText("ANIMALES");

        jLabel11.setFont(new java.awt.Font("MS Gothic", 1, 44)); // NOI18N
        jLabel11.setText("REGISTRO DE ANIMALES");

        jPanel4.setBackground(new java.awt.Color(210, 215, 159));

        lblFotoAnimal.setBackground(new java.awt.Color(238, 227, 203));
        lblFotoAnimal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFotoAnimal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblFotoAnimal.setOpaque(true);

        btnExaminarFoto.setBackground(new java.awt.Color(255, 253, 227));
        btnExaminarFoto.setFont(new java.awt.Font("MS Gothic", 0, 16)); // NOI18N
        btnExaminarFoto.setText("EXAMINAR");

        jLabel6.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel6.setText("NOMBRE:");

        jLabel13.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel13.setText("GENERO:");

        jLabel15.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel15.setText("ESPECIE:");

        comboEspecie.setBackground(new java.awt.Color(255, 253, 227));
        comboEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la especie", "Mamíferos", "Aves", "Reptiles", "Ranas y sapos", "Peces", "Ciempiés y milpiés", "Arañas y alacranes", "Insectos", "Cangrejos y camarones", "Estrellas y erizos", "Caracoles, almejas y pulpos", "Lombrices y gusanos marinos", "Rotíferos", "Gusanos planos", "Medusas y corales", "Esponjas", "Otro..." }));

        buttonGroupGenero.add(btnhembra);
        btnhembra.setText("HEMBRA");

        buttonGroupGenero.add(btnmacho);
        btnmacho.setText("MACHO");

        txtnombreanimal.setBackground(new java.awt.Color(255, 253, 227));

        jLabel17.setFont(new java.awt.Font("Microsoft Himalaya", 1, 22)); // NOI18N
        jLabel17.setText("FECHA DE NACIMIENTO:");

        calendarNacimiento.setBackground(new java.awt.Color(255, 253, 227));

        txtOtraEspecie.setBackground(new java.awt.Color(255, 253, 227));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel6))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnombreanimal, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboEspecie, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(btnhembra)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnmacho))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOtraEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calendarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(lblFotoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExaminarFoto)
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtnombreanimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17))
                                    .addComponent(calendarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnhembra)
                                    .addComponent(jLabel13)
                                    .addComponent(btnmacho))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtOtraEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(lblFotoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExaminarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregar)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(53, 53, 53))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 100, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(447, 447, 447)
                    .addComponent(txtidHabitatNoborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(70, 70, 70)
                    .addComponent(txtidCuidadorNoborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtidAnimalNoborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(447, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(315, 315, 315)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtidHabitatNoborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtidCuidadorNoborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtidAnimalNoborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(291, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExaminarFoto;
    private javax.swing.JButton btnSeleccionarCuidador;
    private javax.swing.JButton btnSeleccionarHabitat;
    private javax.swing.JRadioButton btnhembra;
    private javax.swing.JRadioButton btnmacho;
    private javax.swing.JButton btnseleccionardlgCui;
    private javax.swing.JButton btnseleccionardlgHab;
    private javax.swing.ButtonGroup buttonGroupGenero;
    private com.toedter.calendar.JDateChooser calendarNacimiento;
    private javax.swing.JComboBox<String> comboEspecie;
    private javax.swing.JDialog jDlgCuidador;
    private javax.swing.JDialog jDlgHabitat;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblFotoAnimal;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lbltitulo1;
    private javax.swing.JTable tabladlgCuidador;
    private javax.swing.JTable tabladlgHabitat;
    private javax.swing.JTextField txtNombreCuidador;
    private javax.swing.JTextField txtOtraEspecie;
    private javax.swing.JTextField txtTipoHabitat;
    private javax.swing.JTextField txtTipoSangre;
    private javax.swing.JTextField txtUbicacion;
    private javax.swing.JTextField txtbuscardlgCui;
    private javax.swing.JTextField txtbuscardlgHab;
    private javax.swing.JTextField txtidAnimalNoborrar;
    private javax.swing.JTextField txtidCuidadorNoborrar;
    private javax.swing.JTextField txtidHabitatNoborrar;
    private javax.swing.JTextField txtnombreanimal;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public void setBtnAgregar(JButton btnAgregar) {
        this.btnAgregar = btnAgregar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnExaminarFoto() {
        return btnExaminarFoto;
    }

    public void setBtnExaminarFoto(JButton btnExaminarFoto) {
        this.btnExaminarFoto = btnExaminarFoto;
    }

    public JButton getBtnSeleccionarCuidador() {
        return btnSeleccionarCuidador;
    }

    public void setBtnSeleccionarCuidador(JButton btnSeleccionarCuidador) {
        this.btnSeleccionarCuidador = btnSeleccionarCuidador;
    }

    public JButton getBtnSeleccionarHabitat() {
        return btnSeleccionarHabitat;
    }

    public void setBtnSeleccionarHabitat(JButton btnSeleccionarHabitat) {
        this.btnSeleccionarHabitat = btnSeleccionarHabitat;
    }

    public JRadioButton getBtnhembra() {
        return btnhembra;
    }

    public void setBtnhembra(JRadioButton btnhembra) {
        this.btnhembra = btnhembra;
    }

    public JRadioButton getBtnmacho() {
        return btnmacho;
    }

    public void setBtnmacho(JRadioButton btnmacho) {
        this.btnmacho = btnmacho;
    }

    public JButton getBtnseleccionardlgCui() {
        return btnseleccionardlgCui;
    }

    public void setBtnseleccionardlgCui(JButton btnseleccionardlgCui) {
        this.btnseleccionardlgCui = btnseleccionardlgCui;
    }

    public JButton getBtnseleccionardlgHab() {
        return btnseleccionardlgHab;
    }

    public void setBtnseleccionardlgHab(JButton btnseleccionardlgHab) {
        this.btnseleccionardlgHab = btnseleccionardlgHab;
    }

    public ButtonGroup getButtonGroupGenero() {
        return buttonGroupGenero;
    }

    public void setButtonGroupGenero(ButtonGroup buttonGroupGenero) {
        this.buttonGroupGenero = buttonGroupGenero;
    }

    public JDateChooser getCalendarNacimiento() {
        return calendarNacimiento;
    }

    public void setCalendarNacimiento(JDateChooser calendarNacimiento) {
        this.calendarNacimiento = calendarNacimiento;
    }

    public JComboBox<String> getComboEspecie() {
        return comboEspecie;
    }

    public void setComboEspecie(JComboBox<String> comboEspecie) {
        this.comboEspecie = comboEspecie;
    }

    public JDialog getjDlgCuidador() {
        return jDlgCuidador;
    }

    public void setjDlgCuidador(JDialog jDlgCuidador) {
        this.jDlgCuidador = jDlgCuidador;
    }

    public JDialog getjDlgHabitat() {
        return jDlgHabitat;
    }

    public void setjDlgHabitat(JDialog jDlgHabitat) {
        this.jDlgHabitat = jDlgHabitat;
    }

    public JLabel getLblFotoAnimal() {
        return lblFotoAnimal;
    }

    public void setLblFotoAnimal(JLabel lblFotoAnimal) {
        this.lblFotoAnimal = lblFotoAnimal;
    }

    public JLabel getLbltitulo() {
        return lbltitulo;
    }

    public void setLbltitulo(JLabel lbltitulo) {
        this.lbltitulo = lbltitulo;
    }

    public JLabel getLbltitulo1() {
        return lbltitulo1;
    }

    public void setLbltitulo1(JLabel lbltitulo1) {
        this.lbltitulo1 = lbltitulo1;
    }

    public JTable getTabladlgCuidador() {
        return tabladlgCuidador;
    }

    public void setTabladlgCuidador(JTable tabladlgCuidador) {
        this.tabladlgCuidador = tabladlgCuidador;
    }

    public JTable getTabladlgHabitat() {
        return tabladlgHabitat;
    }

    public void setTabladlgHabitat(JTable tabladlgHabitat) {
        this.tabladlgHabitat = tabladlgHabitat;
    }

    public JTextField getTxtUbicacion() {
        return txtUbicacion;
    }

    public void setTxtUbicacion(JTextField txtUbicacion) {
        this.txtUbicacion = txtUbicacion;
    }

    public JTextField getTxtNombreCuidador() {
        return txtNombreCuidador;
    }

    public JTextField getTxtOtraEspecie() {
        return txtOtraEspecie;
    }

    public void setTxtOtraEspecie(JTextField txtOtraEspecie) {
        this.txtOtraEspecie = txtOtraEspecie;
    }

    public void setTxtNombreCuidador(JTextField txtNombreCuidador) {
        this.txtNombreCuidador = txtNombreCuidador;
    }

    public JTextField getTxtTipoHabitat() {
        return txtTipoHabitat;
    }

    public void setTxtTipoHabitat(JTextField txtTipoHabitat) {
        this.txtTipoHabitat = txtTipoHabitat;
    }

    public JTextField getTxtTipoSangre() {
        return txtTipoSangre;
    }

    public void setTxtTipoSangre(JTextField txtTipoSangre) {
        this.txtTipoSangre = txtTipoSangre;
    }

    public JTextField getTxtbuscardlgCui() {
        return txtbuscardlgCui;
    }

    public void setTxtbuscardlgCui(JTextField txtbuscardlgCui) {
        this.txtbuscardlgCui = txtbuscardlgCui;
    }

    public JTextField getTxtbuscardlgHab() {
        return txtbuscardlgHab;
    }

    public void setTxtbuscardlgHab(JTextField txtbuscardlgHab) {
        this.txtbuscardlgHab = txtbuscardlgHab;
    }

    public JTextField getTxtidAnimalNoborrar() {
        return txtidAnimalNoborrar;
    }

    public void setTxtidAnimalNoborrar(JTextField txtidAnimalNoborrar) {
        this.txtidAnimalNoborrar = txtidAnimalNoborrar;
    }

    public JTextField getTxtidCuidadorNoborrar() {
        return txtidCuidadorNoborrar;
    }

    public void setTxtidCuidadorNoborrar(JTextField txtidCuidadorNoborrar) {
        this.txtidCuidadorNoborrar = txtidCuidadorNoborrar;
    }

    public JTextField getTxtidHabitatNoborrar() {
        return txtidHabitatNoborrar;
    }

    public void setTxtidHabitatNoborrar(JTextField txtidHabitatNoborrar) {
        this.txtidHabitatNoborrar = txtidHabitatNoborrar;
    }

    public JTextField getTxtnombreanimal() {
        return txtnombreanimal;
    }

    public void setTxtnombreanimal(JTextField txtnombreanimal) {
        this.txtnombreanimal = txtnombreanimal;
    }

}
